name: Bash Scripts
on:
  push: null
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      bash-scripts-src: ${{ steps.bash-scripts.outputs.src }}
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      id: bash-scripts
      with:
        filters: 'src:

          - ''tools/bin/**''

          - ''.github/workflows/bash-scripts.yml''

          '
    - name: Run ShellCheck
      if: steps.bash-scripts.outputs.src == 'true'
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
      with:
        scandir: ./tools/bin
        severity: error
